### ISSUE TITLE
Payload required error occurs on search method with filters

### ISSUE THREAD

**Issue by jtakahashi64** [getmetal/metal-ts#18]
Thank you for creating a simple yet powerful product.

When using the search method with filters to retrieve a list of items that match a specific metadata, a "payload required" error occurs. 

```ts
const indexes = (await metal.search({
  filters: [{ field: "key", value: "value" }],
})) as { id: string }[];
```

ref:
https://github.com/getmetal/metal-ts/blob/main/src/metal.ts#L71

I would like to be able to use the filters with the search method to retrieve the list of items that I need to delete using the deleteOne method.

```ts
const indexes = (await metal.search({
  filters: [{ field: "key", value: "value" }],
})) as { id: string }[];

for (const index of indexes) {
  metal.deleteOne(index.id);
}
```

Please consider addressing this issue.

Thank you.

**Comment by softboyjimbo** [comment]
Hey @jtakahashi64 thanks for the issue. This pr, https://github.com/getmetal/metal-ts/pull/24, should address the problem here
