### ISSUE TITLE
Error in return object of search method

### ISSUE THREAD

**Issue by jtakahashi64** [getmetal/metal-ts#19]
Thank you for dev team!

There is an error in the return object of the search method.
The data type is defined as `object[]` in the type definition, but the actual returned value is `{ data: object[] }`.

It seems that we need to use `return data.data` to retrieve the actual data that we are looking for.
https://github.com/getmetal/metal-ts/blob/main/src/metal.ts#L100

Please consider fixing this issue.

Thank you.

**Comment by Czechh** [comment]
Hey @jtakahashi64 ! Thanks for opening the issue.

This will get fixed on the next release!

This PR addresses that https://github.com/getmetal/metal-ts/pull/17

**Comment by Czechh** [comment]
With our latest release we've addressed this issue.

**Comment by jtakahashi64** [comment]
@Czechh Thanks for the quick response!🙌
